analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.480666
  lightness: 0.1874329
  brandColors:
    - '#301F27'
    - '#658877'
    - '#FFCF9A'
    - '#FFFAE9'
    - '#7F432F'
  rhythmicContrast: 0.4967777
typography_spectrum: 0.4119226
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: WaterlooVistas
