name: WaterlooVistas
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4119226
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#301F27'
    - '#658877'
    - '#FFCF9A'
    - '#FFFAE9'
    - '#7F432F'
  brandStrength: 0.480666
  lightness: 0.1874329
  saturation: 0.5
  rhythmicContrast: 0.4967777
purpose: []
