name: stephenvaneman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000003'
    - '#383236'
    - '#fdd130'
    - '#2ab68d'
    - '#a985b6'
  brandStrength: 0.21457695635035634
  lightness: 0.8296864437870681
  saturation: 0.21461330633610487
  rhythmicContrast: 0.4592161439359188
purpose: []
